### ISSUE TITLE
Basic title image

### ISSUE THREAD

**Issue by 73dward5** [palomartechclub/palomartechclub.github.io#15]
![drawing](https://cloud.githubusercontent.com/assets/8504294/7076067/9db51c6a-debb-11e4-9e0e-28713535c803.png)

**Comment by 73dward5** [comment]
![drawing](https://cloud.githubusercontent.com/assets/8504294/7076392/ed52e82c-debd-11e4-94dd-58563daa6617.png)

**Comment by 73dward5** [comment]
![ptc](https://cloud.githubusercontent.com/assets/8504294/7076808/e4d3e626-dec0-11e4-92a9-7b3178746d68.png)

Now I'm just doodling

**Comment by 73dward5** [comment]
Last one did not look good once uploaded. Heres a second attempt
![ptc](https://cloud.githubusercontent.com/assets/8504294/7076860/40f10718-dec1-11e4-8d6a-13f97687e3f8.JPG)

**Comment by 73dward5** [comment]
Last one. I promise. :D
![ptc](https://cloud.githubusercontent.com/assets/8504294/7077259/2161a2f6-dec4-11e4-8ff9-1d16b0963e78.JPG)

**Comment by tobywhughes** [comment]
I really like the first one. I think the last one is an interesting concept but I don't think it quite makes it obvious that its the Palomar Tech Club. Looks closer to PaTomar Tech Club. There should be a color change.

**Comment by tobywhughes** [comment]
Closing this form now since we seem to have agreed on an image. If anybody wants to make a new image we should create a new issue.
