### ISSUE TITLE
How are folders created?

### ISSUE THREAD

**Issue by palomartechclub** [palomartechclub/palomartechclub.github.io#21]
I'm not sure how to create folders. Are new repo's created with a file in it.

**Comment by tobywhughes** [comment]
Generally new repos are created with a Readme file in it.

Here is a stack exchange post about folders:
http://webapps.stackexchange.com/questions/36411/create-a-folder-in-github-via-the-web-interface

**Comment by palomartechclub** [comment]
Got it. Type "foldername.md/" and make sure there is a file in it.
